---
- hosts: all
  tasks:
    - name: install apache (apt)
      when: ansible_distribution == "Debian"
      package:
        name: apache2
        state: latest
    - name: install apache (yum)
      when: ansible_distribution == "CentOS"
      package:
        name: httpd
        state: latest
