---
- hosts: master
  tasks:
   - name: install httpd package
     yum:
       name: httpd
       state: latest
     tags:
       - install
   - name: starting service
     service:
       name: httpd
       state: started
     tags:
       - start
   - name: stop service
     service:
       name: httpd
       state: stopped
     tags:
       - stop
