---
- name: install httpd package
  yum: name={{ pkgs }} state=installed
       

- name: make /etc/hosts entry
  blockinfile:
    path: /etc/hosts
    block: |
      172.31.1.0 webserver1.example.com   webserver2.example.com                  

- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: 
    - '/var/www/html/webserver1'
    - '/var/www/html/webserver2'
    - '/var/log/httpd/webserver1'
    - '/var/log/httpd/webserver1'


- name: Configure index file
  template: src=site1.j2 dest={{site1_config}}
  
  
- name: Configure index file  
  template: src=site2.j2 dest={{site2_config}}


- name: Copy httpd conf file
  template: src=webserver1.conf dest={{httpd_config}}

- name: Copy httpd conf file
  template: src=webserver1.conf dest={{httpd_config}}
  notify: restart

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"


- name: Open ports with firewalld
  firewalld: "service={{item}} permanent=true state=enabled immediate=true"
  with_items: "{{http_firewall_open_services}}"

   
- name: Restart Apache
  service: name=httpd state=started enabled=yes
  



